version: '3'

services:
  vaccine_app:
    container_name: vaccine_app
    build: .
    tty: true
    ports:
      - 3333:3333
      - 7001:7001
    networks:
      - app-network
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql
networks:
  app-network:
    driver: bridge
